'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class All
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FifteenPuzzle.All", GetType(All).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property blocked() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("blocked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property button0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property button3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm.
        '''</summary>
        Friend Shared ReadOnly Property Confirm() As String
            Get
                Return ResourceManager.GetString("Confirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game.
        '''</summary>
        Friend Shared ReadOnly Property Game() As String
            Get
                Return ResourceManager.GetString("Game", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to give up and start new game?.
        '''</summary>
        Friend Shared ReadOnly Property GiveUp_StartNew() As String
            Get
                Return ResourceManager.GetString("GiveUp_StartNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property Icon15() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon15", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moves: {0}.
        '''</summary>
        Friend Shared ReadOnly Property Moves() As String
            Get
                Return ResourceManager.GetString("Moves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property Quit() As String
            Get
                Return ResourceManager.GetString("Quit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure that this was enough puzzle solving for today?.
        '''</summary>
        Friend Shared ReadOnly Property Quit_EnoughToday() As String
            Get
                Return ResourceManager.GetString("Quit_EnoughToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giving up before even trying to solve?.
        '''</summary>
        Friend Shared ReadOnly Property Quit_NotStarted() As String
            Get
                Return ResourceManager.GetString("Quit_NotStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are still puzzle to solve, are you sure want to quit?.
        '''</summary>
        Friend Shared ReadOnly Property Quit_Unsolved() As String
            Get
                Return ResourceManager.GetString("Quit_Unsolved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This puzzle was solved in {0} moves. Do you want to try new one?.
        '''</summary>
        Friend Shared ReadOnly Property Solved() As String
            Get
                Return ResourceManager.GetString("Solved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start new.
        '''</summary>
        Friend Shared ReadOnly Property StartNew() As String
            Get
                Return ResourceManager.GetString("StartNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property StatusNew() As String
            Get
                Return ResourceManager.GetString("StatusNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tadaa!.
        '''</summary>
        Friend Shared ReadOnly Property Tadaa() As String
            Get
                Return ResourceManager.GetString("Tadaa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property tap() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Victory in {0} click(s)!.
        '''</summary>
        Friend Shared ReadOnly Property Victory() As String
            Get
                Return ResourceManager.GetString("Victory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fifteen puzzle - {0}.
        '''</summary>
        Friend Shared ReadOnly Property Window_Title() As String
            Get
                Return ResourceManager.GetString("Window_Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
